spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/elearningplatform
    username: postgres
    password: Manuuh86
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: create-drop

