spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/elearningplatform
    username: postgres
    password: Manuuh86
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  security:
    user:
      name: root
      password: root
#        org.hibernate.dialect.PostgreSQLDialect  ensures that Hibernate generates SQL statements compatible with PostgreSQL syntax and optimizes the database interaction for PostgreSQL's features and capabilities

